name: My First Workflow

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: list Files in Repo
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          lsb_release -a
          tree 

      

  
  
